import uuid
from typing import Protocol

from src.domain.aggregates.team_application import TeamApplication
from src.domain.aggregates.track import Track
from src.domain.entities.member import Member


class ConfirmationServiceProtocol(Protocol):
    async def create_team(self, application: TeamApplication) -> None: ...

    async def submit_team(self, application: TeamApplication) -> None: ...

    async def update_team(self, application: TeamApplication) -> None: ...

    async def delete_member(
        self, application_id: uuid.UUID, member_id: uuid.UUID
    ) -> None: ...

    async def add_member(self, application_id: uuid.UUID, member: Member) -> None: ...

    async def create_rule(self, track: Track) -> None: ...

    async def confirm_team(self, application_id: uuid.UUID) -> None: ...

    async def reject_team(self, application_id: uuid.UUID, reason: str) -> None: ...

    async def get_application(self, track_id: uuid.UUID) -> list[TeamApplication]: ...

    async def get_rule_by_track_id(self, track_id: uuid.UUID) -> Track: ...

    async def get_confirmed_teams_by_track(
        self, track_id: uuid.UUID
    ) -> list[TeamApplication]: ...

    async def confirm_next_from_waitlist(self, track_id: uuid.UUID) -> None: ...

    async def expire_grace_periods(self) -> None: ...
